PROYECTO
JORGE ESTUARDO ALONZO


*1*
1.1
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lillies)
```
1.2
```{r}
yearly=read.csv("deaths_handwashing.csv")
```
1.3

```{r}
yearly
```
*2*
2.1
```{r}
yearly%>%
  mutate(proportion_deaths=births/deaths)
```
*3*
```{r}
  ggplot(yearly, aes(x=year,y=deaths,colour=clinic))+
  geom_line()
```

*4*
4.1
```{r}
monthly=read.csv("deaths_clinic_1.csv")

monthly
```
4.2

```{r}

monthly%>%
  mutate(proportion_deaths=deaths/births)
  

```

4.3
```{r}
head(monthly)
```
4.3.1
```{r}
monthly1=monthly%>%
  mutate(proportion_deaths=deaths/births)
```

```{r}
monthly1
```
4.3.2
```{r}
head(monthly1)
```

*5*
5.1
```{r}

 ggplot(monthly1, aes(x=births,y=deaths))+
  geom_line()


```
5.2

```{r}

 ggplot(monthly1, aes(x=births,y=deaths))+
  geom_line()+labs(title="GRAFICA",x = "Births",y="Deaths")
```
5.3


```{r}
death_by_year=monthly1%>%
  group_by(date)%>%
  summarize(deathss=median(deaths))

death_by_year
```
5.4

```{r}
ggplot(death_by_year,aes(x=date,y=deathss))+geom_col()


```
6.
6.1
```{r}
monthly=monthly1%>%
  mutate(handwashing_started=date >= "1847-01-01")
  
monthly
  
  
```
6.2

```{r}
 ggplot(monthly, aes(x=date,y=proportion_deaths,colour=handwashing_started))+
  geom_line()
```

6.3

```{r}
 ggplot(monthly, aes(x=date,y=proportion_deaths,colour=handwashing_started))+
  geom_line()+labs(title="GRAFICA",x="FECHA",y="PROPORCION",colour="HANDWASHING")
```



7.
7.1
```{r}
month_summary=monthly%>%
  group_by(handwashing_started)%>%
  summarise(mean(proportion_deaths))
month_summary
```

8.

```{r}
t.test(month_summary$`mean(proportion_deaths)`)
```
















